# from functions.get_file_content import get_file_content
from functions.write_file import write_file

print("==========================================")
print(write_file("calculator", "lorem.txt", "wait, this isn't lorem ipsum"))
print("==========================================")
print(write_file("calculator", "pkg/morelorem.txt", "lorem ipsum dolor sit amet"))
print("==========================================")
print(write_file("calculator", "/tmp/temp.txt", "this should not be allowed"))
print("==========================================")

# print("==========================================")
# print(get_file_content("calculator", "lorem.txt"))
# print("==========================================")

# print("==========================================")
# print(get_file_content("calculator", "main.py"))
# print("==========================================")
# print(get_file_content("calculator", "pkg/calculator.py"))
# print("==========================================")
# print(get_file_content("calculator", "/bin/cat"))
# print("==========================================")      

# print("==========================================")
# print(get_files_info("calculator", "."))
# print("==========================================")
# print(get_files_info("calculator", "pkg"))
# print("==========================================")
# print(get_files_info("calculator", "/bin"))
# print("==========================================")
# print(get_files_info("calculator", "../"))
# print("==========================================")
# print(get_files_info("calculator", "calculator"))
# print("==========================================")
# print(get_files_info("calculator", "calculator/pkg"))
# print("==========================================")